### ISSUE TITLE
0001-two-sum.js

### ISSUE THREAD

**Issue by azole** [TaylorLiu11/DataStructureLearning#1]
https://github.com/TaylorLiu11/DataStructureLearning/blob/64c4b5320af9aef261c1086f992aad3e604a2863/0001-two-sum.js#L5

寫法 1 中，這一行的中的 j，如果改成 i+1，例如:

```javascript
for (let j = i+1; j < nums.length; j++) {
```

你覺得會不會更快一點？為什麼？

**Comment by TaylorLiu11** [comment]
是因為這樣的話就不用再創造一個新的記憶體空間，去記憶一個新的整數嗎？

**Comment by azole** [comment]
不是，j 還是 j 啊，不要用推測的，讓我們來算算看：

nums = [1, 2, 7, 9, 11, 15];
target = 26

以這個案例來說，答案是 [4, 5]

你試著算算看：
-  j = 1 ： if ((nums[i] + nums[j]) === target)  這個判斷式要判斷幾次，才會有答案？
- j = i+1 這種寫法， if 這個判斷式，要判斷幾次才會有答案？

然後回答看看，為什麼數字會有差異？

**Comment by TaylorLiu11** [comment]
懂了，因為前面的數已經加過，在這裡如果依舊設成 j = 1 的話會重複很多不需要的部分，所以設成 j = i + 1 會是我在方法 2 裡想要做的。
